Explorer Display for mobile & Extension Points
vtex-apps/category-menu pull request #111
Opened 2021-08-05 14:57 UTC by cristian-milea

#### What problem is this solving?

Offer a new type of menu for mobileMode, providing navigation inside the menu. This is good for deep levels of categories, keeping the user focused one category at a time.

Also, added Before and After extension points.

#### How to test it?

```
"category-menu#main": {
    "props": {
      "showAllDepartments": true,
      "showSubcategories": true,
      "menuDisposition": "left",
      "mobileMode": true,
      "mobileDisplayType": "explorer"
    },
    "blocks": [
      "before-menu",
      "after-menu"
    ]
  },
  "before-menu": {
    "children": [
      "rich-text#menu-before-child"
    ]
  },
  "rich-text#menu-before-child": {
    "props": {
      "text": " --- add enything before"
    }
  },
```

[Workspace](https://cristi--elefant.myvtex.com/)

#### Screenshots or example usage:

![Screen Recording 2021-08-05 at 5 47 53 PM](https://user-images.githubusercontent.com/4988454/128370955-c21c9e69-c3e7-46fa-9dca-fa9f5a7a4253.gif)

#### Describe alternatives you've considered, if any.

This type of navigation is not possible using any other IO components.

#### Related to / Depends on
* Lodash and used tree shaking imports.

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/Y3l2CbTxVd6oC47Bq5/giphy.gif)

2021-08-10 14:16 UTC, camilavcoutinho requested changes

2021-08-10 14:16 UTC, camilavcoutinho commented on messages/pt.json
> +  "store/category-menu.explorer.back": "Regresar",
```suggestion
  "store/category-menu.explorer.back": "Voltar",
```

2021-08-10 14:16 UTC, camilavcoutinho commented on messages/es.json
> +  "store/category-menu.explorer.back": "Regresar",
```suggestion
  "store/category-menu.explorer.back": "Atrás",
```

2021-08-18 17:30 UTC, camilavcoutinho approved these changes

2021-09-21 20:39 UTC, igorbrasileiro requested changes
Excellent job, @cristian-milea! 
As far as I understand, this PR seems to be a breaking change to our APP, since it changes where the title appears.

Also, I left some comments. Can you take a look there and help me?

2021-09-21 20:39 UTC, igorbrasileiro commented on package.json
> +    "eslint-config-vtex": "^12.8.11",
Bump to our latest version: [14.x](https://github.com/vtex/typescript/blob/main/packages/eslint-config-vtex/package.json)

2021-09-21 20:39 UTC, igorbrasileiro commented on store/interfaces.json
> +    "allowed": "*"
I didn't get why you do this. Can you explain?

2021-09-21 20:39 UTC, igorbrasileiro commented on react/utils/constants.js
> +export const DEFAULT_SUBCATEGORIES_LEVELS = 1
Can you migrate to typescript files? `.ts`

2021-09-21 20:39 UTC, igorbrasileiro commented on react/tsconfig.json
> +  "compilerOptions": {
Did you write this by yourself, or `vtex setup` do?

2021-09-21 20:39 UTC, igorbrasileiro commented on react/package.json
> +    "vtex.category-menu": "https://cristi--elefant.myvtex.com/_v/private/typings/linked/v1/vtex.category-menu@2.16.1+build1627629726/public/@types/vtex.category-menu",
This line can't be the type of your workspace. Unlink the app from your current workspace, then run `vtex setup --typings`

2021-09-21 20:39 UTC, igorbrasileiro commented on react/index.tsx
> +          // })}
Does this was intentional?

2021-09-21 20:39 UTC, igorbrasileiro commented on react/index.tsx
> +          </p>
It seems to be a breaking change, right? @victorhmp @icazevedo, can you help here?

2024-08-26 17:46 UTC, closed without merging