Sort subcategories by name
vtex-apps/category-menu pull request #98
Opened 2021-05-11 09:54 UTC by khrizzcristian

#### What problem is this solving?
We have added the possibility to sort subcategories by name.

[Workspace with app linked & sort active](https://menu--biasicom.myvtex.com/)
[Default workspace](https://biasicom.myvtex.com/)

#### Screenshots or example usage:

![Sort PrintScreen](https://user-images.githubusercontent.com/43498488/117796655-f5c29100-b257-11eb-80bc-43262eaf77ef.jpg)

2021-05-24 15:01 UTC, icazevedo approved these changes
LGTM

2021-05-24 18:08 UTC, victorhmp approved these changes

2021-05-31 17:09 UTC, icazevedo requested changes
Hey @khrizzcristian! The danger CI is failing because of a little issue with the changelog. Can you please accept the suggestion? We need this before releasing.

I'm unable to fix it directly since you opened the PR from your master branch. If you had done using a different branch, I would be able to do it.

2021-05-31 17:09 UTC, icazevedo commented on CHANGELOG.md
> +- Add `sortSubcategories` as option for `category-menu`
```suggestion
### Added
- `sortSubcategories` as option for `category-menu`
```

2021-05-31 17:12 UTC, icazevedo approved these changes
I was actually able to do it! Great 😄

2021-05-31 17:22 UTC, khrizzcristian commented
Great. Thank you😁

2021-05-31 18:05 UTC, camilavcoutinho requested changes

2021-05-31 18:17 UTC, camilavcoutinho approved these changes

2021-05-31 18:24 UTC, merged

2021-05-31 18:39 UTC, icazevedo commented
@allcontributors add @khrizzcristian for code